HTTPremadeTrackersData = {
	["Debuffs"] = {
		["Stagger"] = {
		ID = 134336,
		description = "Debuff applied by Dragonknight's Stone Giant ability, increases enemies' damage taken by 65 per stack, up to 3 stacks, tracker changes color based on amount of stacks",
		text = "+65/130/195 damage increase",
		textWhenMissing = "Stagger missing",
		color = {1,0,0,1},
		color2 = {1,1,0,1},
		color3 = {0,1,0,1},
		onlyPlayer = false,
		skills = {31816,133027},
		},
		["Alkosh"] = {
		ID = 75753,
		description = "Debuff applied by Roar of Alkosh item set, reduces enemies' resistances by amount of your weapon damage, capped at 3000",
		text = "+X penetration",
		textWhenMissing = "Alkosh missing",
		color = {0.62,0,1,1},
		onlyPlayer = false,
		itemSet = {"|H1:item:73360:364:50:26845:370:50:4:0:0:0:0:0:0:0:1:45:0:1:0:421:0|h|h"},
		itemSetNumber = 3,
		itemSetToShow = "Roar of Alkosh",
		duration = 10,
		},
		["Flame Weakness"] = {
		ID = 142610,
		description = "One of Catalyst's 3 debuffs, increases target's critical damage taken by 3% after they've been struck by flame damage, lasts 3 seconds",
		text = "+3% critical damage",
		textWhenMissing = "Flame Weakness missing",
		color = {1,148/255,87/255,1},
		onlyPlayer = false,
		itemSet = {"|H1:item:164876:364:50:0:0:0:16:0:0:0:0:0:0:0:2049:107:0:1:0:9700:0|h|h"},
		itemSetNumber = 3,
		itemSetToShow = "Elemental Catalyst"
		},
		["Frost Weakness"] = {
		ID = 142652,
		description = "One of Catalyst's 3 debuffs, increases target's critical damage taken by 3% after they've been struck by frost damage, lasts 3 seconds",
		text = "+3% critical damage",
		textWhenMissing = "Frost Weakness missing",
		color = {105/255, 240/255, 1,1},
		onlyPlayer = false,
		itemSet = {"|H1:item:164876:364:50:0:0:0:16:0:0:0:0:0:0:0:2049:107:0:1:0:9700:0|h|h"},
		itemSetNumber = 3,
		itemSetToShow = "Elemental Catalyst"
		},
		["Shock Weakness"] = {
		ID = 142653,
		description = "One of Catalyst's 3 debuffs, increases target's critical damage taken by 3% after they've been struck by shock damage, lasts 3 seconds",
		text = "+3% critical damage",
		textWhenMissing = "Shock Weakness missing",
		color = {112/255, 148/255, 1,1},
		onlyPlayer = false,
		itemSet = {"|H1:item:164876:364:50:0:0:0:16:0:0:0:0:0:0:0:2049:107:0:1:0:9700:0|h|h"},
		itemSetNumber = 3,
		itemSetToShow = "Elemental Catalyst"
		},
		["Minor Mangle"] = {
		ID = 61733,
		description = "Effect applied by Pulsar skill and status effect from bleed damage, reduces enemies' max health by 10%",
		text = "-10% max health",
		textWhenMissing = "Minor Mangle missing",
		color = {0.36,0,0.04,1},
		onlyPlayer = false,
		},
		["Off-Balance/Off-Balance Immunity"] = {
		ID = {
			[1] = 62988, --long wall
			[2] = 63108, --dodge roll
			[3] = 130145, --mag birb
			[4] = 23808, --lava whip
			[5] = 20806, --molten whip
			[6] = 34117, --flame lash
			[7] = 45902, --generic off balance (interrupting with deep breath, heavy block etc)
			[8] = 120014, --iron atronach
			[9] = 25256, --veiled strike
			[10] = 34733, --surprise attack
			[11] = 34737, --concealed weapon
			[12] = 49205, --focused charge
			[13] = 49213, --explosive charge
			[14] = 130129, --unmorphed birb
			[15] = 130145, --stam birb
			[16] = 125750, --ruinous scythe
			[17] = 131562, --dizzy swing
			[18] = 62968, --unmorphed wall
			[19] = 39077, --explosive wall
			[20] = 134599, --Off-Balance immunity
		},
		description = "Tracker that tracks Off-Balance effect on the enemy, and after that effect expires tracks immunity to Off-Balance with a different color",
		text = "Off-Balance applied",
		textWhenMissing = "Off-Balance ready",
		color = {0,0.7,0.5,1},
		color2 = {1,0.02,0,1},
		onlyPlayer = false,
		icon = "/esoui/art/icons/ability_debuff_offbalance.dds",
		},
		["Engulfing Flames"] = {
		ID = 31104,
		description = "Debuff applied by Dragonknights, increases enemies' fire damage taken, scales with your max magicka and spell damage, up to maximum value of 10%",
		text = "+X% fire damage",
		textWhenMissing = "Engulfing Flames missing",
		color = {1,0.4,0,1},
		onlyPlayer = false,
		skills = {20930}
		},
		["Crusher"] = {
		ID = 17906,
		description = "Debuff applied by Crusher weapon enchantment, reduces enemies' armor by a certain amount, depending on traits and quality of your weapon, maximum 2108 value without Torug",
		text = "+2108 penetration",
		textWhenMissing = "Crusher missing",
		color = {0,1,1,1},
		onlyPlayer = false,
		},
		["Weapon Skill"] = {
		ID = {39018,39028,39012,38695,28876,38689,28807,28849,28854,39067,39073,39053},
		description = "Tracker that will adjust to skills you're casting. It's supposed to track damage over time ground based ability from any weapon skill tree (Endless Hail from Bow Tree, Wall of Elements from Destruction Staff Tree etc) The text will display how many Crushers will the skill apply in its remaining duration",
		text = "X crushers left",
		textWhenMissing = "Weapon Skill missing",
		color = {0,0.5,0.7,1},
		onlyPlayer = false,
		icon = "/esoui/art/icons/ability_destructionstaff_003_b.dds",
		},
		["Minor Vulnerability"] = {
		ID = 79717,
		description = "Debuff applied by Shock damage status effect and other various skills and item sets. Increases enemies' damage taken by 5%",
		text = "+5% damage taken",
		textWhenMissing = "Minor Vulnerability missing",
		color = {0.4,0.1,0.9,1},
		onlyPlayer = false,
		},
		["Minor Magickasteal"] = {
		ID = 88401,
		description = "Debuff applied by Magic damage status effect and other various skills. Causes attacks against affected enemies' to restore 168 Magicka every 1 second",
		text = "+168 magicka per second",
		textWhenMissing = "Minor Magickasteal missing",
		color = {0.2,0.6,0.7,1},
		onlyPlayer = false,
		},
		["Minor Brittle"] = {
		ID = 145975,
		description = "Debuff applied by Frost damage status effect only when you're wielding Ice Staff. Increases enemies' critical damage taken by 10%",
		text = "+10% critical damage",
		textWhenMissing = "Minor Brittle missing",
		color = {0.74,1,0.5,1},
		onlyPlayer = false,
		},
		["Crystal Weapon"] = {
		ID = 143808,
		description = "Debuff applied by Sorcerer's Crystal Weapon skill, reduces enemies' armor by 1000",
		text = "+1000 penetration",
		textWhenMissing = "Crystal Weapon missing",
		color = {0.23,0.35,0.69,1},
		onlyPlayer = false,
		skill = {46331},
		},
		["Tremorscale"] = {
		ID = 80866,
		description = "Debuff applied by Tremorscale item set. Reduces enemies' physical resistance by 2395",
		text = "+2395 physical penetration",
		textWhenMissing = "Tremorscale missing",
		color = {0.69,0.58,0.34,1},
		onlyPlayer = false,
		itemSet = {"|H1:item:94551:364:50:0:0:0:0:0:0:0:0:0:0:0:1:67:0:1:0:10000:0|h|h"},
		itemSetNumber = 2,
		itemSetToShow = "Tremorscale"
		},
		["Minor Breach"] = {
		ID = 61742,
		description = "Debuff applied by Physical damage status effect and other various skills and item sets. Decreases enemies' armor by 2974",
		text = "+2974 penetration",
		textWhenMissing = "Minor Breach missing",
		color = {0.23,0.35,0.69,1},
		onlyPlayer = false,
		},
		["Major Breach"] = {
		ID = 61743,
		description = "Debuff applied by various skills and item sets. Decreases enemies' armor by 5948",
		text = "+5948 penetration",
		textWhenMissing = "Major Breach missing",
		color = {0.73,0.56,1,1},
		onlyPlayer = false,
		},
		["Major Maim"] = {
		ID = 61725,
		description = "Debuff applied by various skills and item sets. Decreases enemies' damage dealt by 10%",
		text = "-10% damage done",
		textWhenMissing = "Major Maim missing",
		color = {0.56,0,0.16,1},
		onlyPlayer = false,
		},
		["Minor Maim"] = {
		ID = 61723,
		description = "Debuff applied by Frost damage status effect and other various skills and item sets. Decreases enemies' damage dealt by 5%",
		text = "-5% damage done",
		textWhenMissing = "Minor Maim missing",
		color = {0.8,0.29,0.44,1},
		onlyPlayer = false,
		},

	},
	["Buffs"] = {
		["Immovable"] = {
		ID = 126583,
		description = "Buff applied by Immovable skill in Heavy Armor Skill Line, increases your block mitigation",
		text = "Block mitigation increased",
		textWhenMissing = "Immovable missing",
		color = {0,0.3,1,1},
		},
		["Minor Courage"] = {
		ID = 147417,
		description = "Buff applied by Claw of Yolnahkriin item set and Werewolf Pack Leader skill, increases your weapon and spell damage by 215",
		text = "+215 power",
		textWhenMissing = "Minor Courage missing",
		color = {0.1,0.7,0.1,1},
		},
		["Dragon Blood"] = {
		ID = 32745,
		description = "Dragonknigt's skill, tracks duration of Green Dragon Blood",
		text = "+12% healing received",
		textWhenMissing = "Dragon Blood missing",
		color = {1,0.4,0.7,1},
		icon = "/esoui/art/icons/ability_dragonknight_011_b.dds",
		},
		["Major Resolve"] = {
		ID = 61694,
		description = "Buff applied by various skills and item sets, increases your armor by 5948",
		text = "+5948 armor",
		textWhenMissing = "Major Resolve missing",
		color = {1,0.52,0.21,1},
		},
		["Bull Netch"] = {
		ID = 86058,
		description = "Warden's skill, tracks duration of Bull Netch",
		text = "Bull Netch active",
		textWhenMissing = "Bull Netch missing",
		color = {0.23,1,0,1},
		},
		["Polar Wind"] = {
		ID = 90835,
		description = "Warden's skill, tracks duration of Polar Wind",
		text = "Polar Wind active",
		textWhenMissing = "Polar Wind missing",
		color = {0.77,0.85,0.72,1},
		},
		["Bound Aegis"] = {
		ID = 24163,
		description = "Sorcerer's skill, tracks duration of Bound Aegis",
		text = "+40% block mitigation",
		textWhenMissing = "Bound Aegis missing",
		color = {0.55,0,0.8,1},
		skill = {24163},
		},
		["Dark Deal"] = {
		ID = 114908,
		description = "Sorcerer's skill, tracks duration of Dark Deal",
		text = "Dark Deal active",
		textWhenMissing = "Dark Deal missing",
		color = {0,0.12,0.54,1},
		skill = {24595},
		},
		["Crystal Weapon"] = {
		ID = 46331,
		description = "Sorcerer's skill, tracks duration of Crystal Weapon effect on you (the effect that causes your next light attack to apply Crystal Weapon debuff)",
		text = "Crystal Weapon ready",
		textWhenMissing = "Crystal Weapon missing",
		color = {0.34,0.1,0.91,1},
		},
		["Sacred Ground"] = {
		ID = {77082,31759},
		description = "Templar's skill, tracks if you're standing in your own Cleansing Ritual, Rune Focus or Rite of Passage to show if you're getting benefit from Sacred Ground passive",
		text = "+10% block mitigation",
		textWhenMissing = "Sacred Ground missing",
		color = {1,0.93,0.57,1},
		},
		["Rune Focus bonus"] = {
		ID = 112145,
		description = "Templar's skill, tracks if you're standing in your Rune Focus to show if you're getting bonus 2974 armor",
		text = "+2974 armor",
		textWhenMissing = "Rune Focus missing",
		color = {0.97,0.82,0.22,1},
		},
		["Spirit Guardian bonus"] = {
		ID = 118912,
		description = "Necromancer's skill, tracks duration of Spirit Guardian",
		text = "Spirit Guardian active",
		textWhenMissing = "Spirit Guardian missing",
		color = {0.67,0.52,0.81,1},
		},
		["Dark Cloak"] = {
		ID = 25377,
		description = "Nightblade's skill, tracks duration of Dark Cloak",
		text = "Dark Cloak active",
		textWhenMissing = "Dark Cloak missing",
		color = {0.8,0,0.16,1},
		},
		["Leeching Strikes"] = {
		ID = 36908,
		description = "Nightblade's skill, tracks duration of Leeching Strikes",
		text = "Leeching Strikes active",
		textWhenMissing = "Leeching Strikes missing",
		color = {0.58,0.12,0.12,1},
		},
		["Minor Heroism"] = {
		ID = 61708,
		description = "Buff applied by various skills and item sets. Grants you +1 ultimate every 1.5 second",
		text = "+1 ultimate every 1.5 second",
		textWhenMissing = "Minor Heroism missing",
		color = {1,0.98,0.5,1},
		},
		["Major Heroism"] = {
		ID = 61709,
		description = "Buff applied by various skills and item sets. Grants you +3 ultimate every 1.5 second",
		text = "+3 ultimate every 1.5 second",
		textWhenMissing = "Major Heroism missing",
		color = {1,0.74,0.58,1},
		},
		["Minor Resolve"] = {
		ID = 61693,
		description = "Buff applied by various skills and item sets. Grants you +2974 armor",
		text = "+2974 armor",
		textWhenMissing = "Minor Resolve missing",
		color = {1,0.72,0.54,1},
		},
		["Minor Mending"] = {
		ID = 61710,
		description = "Buff applied by various skills and item sets. Grants you +8% healing done",
		text = "+8% healing done",
		textWhenMissing = "Minor Mending missing",
		color = {0.64,1,0.67,1},
		},
		["Major Mending"] = {
		ID = 61711,
		description = "Buff applied by various skills and item sets. Grants you +16% healing done",
		text = "+16% healing done",
		textWhenMissing = "Major Mending missing",
		color = {0,1,0.08,1},
		},
		["Minor Vitality"] = {
		ID = 61549,
		description = "Buff applied by various skills and item sets. Grants you +8% healing taken",
		text = "+8% healing taken",
		textWhenMissing = "Minor Vitality missing",
		color = {1,0.5,0.45,1},
		},
		["Major Vitality"] = {
		ID = 61713,
		description = "Buff applied by various skills and item sets. Grants you +16% healing taken",
		text = "+16% healing taken",
		textWhenMissing = "Major Vitality missing",
		color = {1,0.05,0,1},
		},
		["Puncturing Remedy"] = {
		ID = 100575,
		description = "Buff applied by Puncturing Remedy set (Master's Sword and Board). Tracker displays bonus armor applied by the buff",
		text = "+X armor",
		textWhenMissing = "Puncturing Remedy missing",
		color = {0.1,0.8,0.4,1},
		},

	},
	["Cooldowns"] = {
		["Void Pull"] = {
		ID = 147747,
		description = "Effect triggered by Void Bash set - Vateshran's Sword and Board. Using Power Bash pulls enemies withing 12 meters range towards you and applies Major Maim to them 2 seconds after initial pull",
		text = "Void Pull on cooldown",
		textWhenMissing = "Use Power Bash",
		color = {0.52,0.41,1,1},
		skills = {28365,38455,38452},
		itemSet = {"|H0:item:169996:363:50:0:0:0:0:0:0:0:0:0:0:0:2048:10:0:0:0:0:0|h|h","|H0:item:169879:362:50:0:0:0:0:0:0:0:0:0:0:0:2048:10:0:0:0:0:0|h|h"},
		itemSetNumber = 2,
		itemSetToShow = "Void Bash (Vateshran Sword and Board)",
		duration = 13,
		},
		["Lady Thorn"] = {
		ID = 141905,
		description = "Effect triggered by Lady Thorn set. Using an ability that costs health spawns a blood ball for 10 seconds. You or an ally can activate the Sanguine Burst synergy to deal disease damage and apply Major Maim to enemies around you",
		text = "Lady Thorn on cooldown",
		textWhenMissing = "Use Health-costing ability",
		color = {0.81,0,0.2,1},
		itemSet = {"|H1:item:167116:364:50:68343:370:50:16:0:0:0:0:0:0:0:1:67:0:1:0:1242:0|h|h"},
		itemSetNumber = 2,
		itemSetToShow = "Lady Thorn",
		duration = 10,
		icon = "/esoui/art/icons/ability_u23_bloodball_chokeonit.dds",
		},
		["Tremorscale"] = {
		ID = 80865,
		description = "Effect triggered by Tremorscale set. Activating a taunt ability causes a duneripper to burst from the ground beneath the target after 1 second, dealing damage and reducing their physical resistance for 8 seconds",
		text = "Tremorscale on cooldown",
		textWhenMissing = "Use taunt",
		color = {0.7, 0.54, 0.35,1},
		itemSet = {"|H1:item:94551:364:50:0:0:0:0:0:0:0:0:0:0:0:1:67:0:1:0:10000:0|h|h"},
		itemSetNumber = 2,
		itemSetToShow = "Tremorscale",
		duration = 7,
		},

		["Yolnahkriin"] = {
		ID = 121878,
		description = "Effect triggered by Claw of Yolnahkriin set. Taunting an enemy applies Minor Courage to you and 11 group members, increasing Weapon and Spell Damage by 215 for 15 seconds",
		text = "Yolnahkriin on cooldown",
		textWhenMissing = "Use taunt",
		color = {1, 0.5, 0, 1},
		itemSet = {"|H1:item:150869:364:50:68343:370:50:13:0:0:0:0:0:0:0:1:86:0:1:0:8321:0|h|h", "|H1:item:149648:364:50:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:10000:0|h|h"},
		itemSetNumber = 3,
		itemSetToShow = "Claw of Yolnahkriin",
		duration = 8,
		icon = "/esoui/art/icons/gear_sunspire_heavy_helmet_a.dds",
		},

		["Olorime"] = {
		ID = 109084,
		description = "Effect trigger by Vestment of Olorime set. Casting an ability that leaves effect on the ground creates a yellow circle on the ground for 5 seconds. You and allies standing in the circle gain Major Courage for 20 seconds, increasing your Weapon and Spell Damage by 430",
		text = "Olorime on cooldown",
		textWhenMissing = "Cast ground ability",
		color = {0.01, 1, 0, 1},
		itemSet = {"|H1:item:138531:364:50:26845:370:50:2:0:0:0:0:0:0:0:2049:73:0:1:0:406:0|h|h", "|H1:item:137358:364:50:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:10000:0|h|h"},
		itemSetNumber = 3,
		itemSetToShow = "Vestment of Olorime",
		duration = 10,
		icon = "/esoui/art/icons/gear_welkynar_light_head_a.dds",
		},

		["Mountain's Blessing"] = {
		ID = 45005,
		description = "Dragonknight's passive in Earthen Heart tree, using an ability from that tree grants you 3 ultimate",
		text = "+3 ultimate on cooldown",
		textWhenMissing = "Use Earthen Heart ability",
		color = {0.72, 0.15, 0, 1},
		duration = 6,
		icon = "/esoui/art/icons/ability_dragonknight_024.dds",
		},

		["Savage Beast"] = {
		ID = 88513,
		description = "Warden's passive in Animal Companions tree, using an ability from that tree grants you 4 ultimate",
		text = "+4 ultimate on cooldown",
		textWhenMissing = "Use Animal Companions ability",
		color = {0, 0.24, 0.72, 1},
		duration = 8,
		icon = "/esoui/art/icons/passive_warden_009.dds",
		},

		["Transfer"] = {
		ID = 45146,
		description = "Nightblade's passive in Siphoning tree, using an ability from that tree grants you 2 ultimate",
		text = "+2 ultimate on cooldown",
		textWhenMissing = "Use Siphoning ability",
		color = {0.66, 0.2, 0.82, 1},
		duration = 4,
		icon = "/esoui/art/icons/passive_sorcerer_002.dds",
		},

		["Corpse Consumption"] = {
		ID = 120612,
		description = "Necromancer's passive in Living Death tree, using an ability that targets corpse grants you 10 ultimate",
		text = "+10 ultimate on cooldown",
		textWhenMissing = "Use ability on corpse",
		color = {0.72, 0, 0.13, 1},
		duration = 16,
		icon = "/esoui/art/icons/passive_necromancer_011.dds",
		},

		["Prism"] = {
		ID = 45217,
		description = "Templar's passive in Dawn's Wrath tree, using an ability from that tree grants you 3 ultimate",
		text = "+3 ultimate on cooldown",
		textWhenMissing = "Use Dawn's Wrath ability",
		color = {1, 0.86, 0.47, 1},
		duration = 6,
		icon = "/esoui/art/icons/ability_templar_031.dds",
		},
		["Encratis's Behemoth"] = {
		ID = 151034,
		description = "Effect triggered by Encratis's Behemoth set. Dealing flame damage creates grants you a 12 meter aura for 12 seconds. Enemies inside that aura take 5% more flame damage. Allies inside that aura takes 5% less flame damage",
		text = "Encratis's Behemoth on cooldown",
		textWhenMissing = "Deal flame damage",
		color = {1, 0.6, 0.3, 1},
		duration = 15,
		itemSet = {"|H1:item:171612:364:50:68343:370:50:0:0:0:0:0:0:0:0:1:67:0:1:0:375:0|h|h"},
		itemSetToShow = "Encratis's Behemoth",
		}
	}
}